
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: ali_amrah
  password: click227
  host: localhost

development:
  <<: *default
  database: sales_management_development


test:
  <<: *default
  database: sales_management_test

production:
  <<: *default
  database: sales_management_production
  username: sales_management
  password: <%= ENV['SALES_MANAGEMENT_DATABASE_PASSWORD'] %>
